version: '3'
networks:
  db_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.180.0/24
  api_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.170.0/24
services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    networks:
      db_net:
        ipv4_address: 192.168.180.2
    volumes:
      - ./db/mysql.conf:/etc/mysql/mysql.conf.d
      - ./db/todo:/home/todo
      - ./db/initdb:/docker-entrypoint-initdb.d
      # - ./db/log:/var/lib/mysql
    environment:
      MYSQL_DATABASE: todo_dev
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    user: root
    volumes:
      - ./front:/usr/src/app
    command: sh -c "cd todo_app && npm run dev"
    ports:
      - "3000:3000"
    tty: true
    environment:
      BASE_URL: "http://192.168.170.2"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      api_net:
        ipv4_address: 192.168.170.2
    # command: sh -c "go run ."
    ports:
      - "8080:8080"
    volumes:
      - ./api:/go/src/api/
    tty: true
    environment:
      TEST_MODE: "true"
      MYSQL_DATABASE: "todo_dev"
      MYSQL_TEST_DATABASE: "todo_test"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_HOST: 192.168.180.2
      MYSQL_PORT: 3306
    depends_on:
      - db
